#! /usr/bin/env bash
set -euo pipefail

tmp_dir=$(mktemp -d)
trap "rm -rf ${tmp_dir}" EXIT

base=(
    "linux"
    "linux-firmware"
    "base"
    "base-devel"
    "grub"
    "os-prober"
    "efibootmgr"
    "git"
    "man-db"
    "yay-bin"
    "networkmanager"
    "unzip"
    "openssh"
    "libnotify"
    "ufw"
    "lm_sensors"
    "stow"
)

cpu=(
    "amd-ucode"
)

gpu=(
    "nvtop"
)

sound=(
    "alsa-utils"
    "pipewire"
    "pipewire-alsa"
    "pipewire-pulse"
    "pipewire-jack"
    "playerctl"
    "pavucontrol"
)

sway=(
    "sway"
    "swaybg"
    "swaylock"
    "waybar"
    "wmenu"
    "wl-clipboard"
    "slurp"
    "grim"
    "xorg-xwayland"
)

gui=(
    "gammastep"
    "dunst"
)

utilities=(
    "htop"
    "lf"
    "sxiv"
    "zathura-pdf-mupdf"
    "mpv"
    "lxappearance"
    "jq"
)

terminal=(
    "zsh"
    "zsh-syntax-highlighting"
    "tmux"
)

nvim=(
    "neovim"
    "python-pynvim"
    "nodejs"
    "bun-bin"
    "fd"
    "ripgrep"
)

qemu=(
    "virt-manager"
    "qemu-desktop"
    "libvirt"
    "iptables-nft"
    "dnsmasq"
    "openbsd-netcat"
)

entertainment=(
    "firefox"
    "yt-dlp"
)

fonts=(
    "ttf-dejavu"
    "ttf-fira-code"
)

gtk_theme=(
    "gruvbox-dark-gtk"
    "papirus-icon-theme"
    "vimix-cursors"
)

# Change for each hardware
firmware=(
    "ast-firmware"
    "upd72020x-fw"
    "linux-firmware-qlogic"
    "wd719x-firmware"
    "aic94xx-firmware"
)

packages_to_install=(
    "${base[@]}"
    "${sway[@]}"
    "${cpu[@]}"
    "${gpu[@]}"
    "${sound[@]}"
    "${gui[@]}"
    "${utilities[@]}"
    "${terminal[@]}"
    "${nvim[@]}"
    "${qemu[@]}"
    "${entertainment[@]}"
    "${fonts[@]}"
    "${gtk_theme[@]}"
    "${firmware[@]}"
)

ensure_aur_pkg_is_installed() {
    repo_dir="${1}"
    repo_url="${2}"

    if command -v "${3}" &> /dev/null; then
        return
    fi

    [[ ! -d "${repo_dir}" ]] && git clone "${repo_url}" "${repo_dir}"
    (cd "${repo_dir}" && makepkg -si)
    rm -rf "${repo_dir}"
}

ensure_suckless_pkg_is_installed() {
    repo_dir="${1}"
    repo_url="${2}"

    if command -v "${3}" &> /dev/null; then
        return
    fi

    [[ ! -d "${repo_dir}" ]] && git clone "${repo_url}" "${repo_dir}"
    (cd "${repo_dir}" && sudo make install clean)
}


ensure_yay_is_installed() {
    pkg_name="yay"
    repo_dir="${tmp_dir}/yay-bin"
    repo_url="https://aur.archlinux.org/yay-bin.git"

    ensure_aur_pkg_is_installed "${repo_dir}" "${repo_url}" "${pkg_name}"
}

ensure_st_is_installed() {
    pkg_name="st"
    repo_dir="${tmp_dir}/st"
    repo_url="https://github.com/PabloVarg/st"

    ensure_suckless_pkg_is_installed "${repo_dir}" "${repo_url}" "${pkg_name}"
}

sync_packages() {
    mkdir -p "${tmp_dir}/sync"

    tmp_a=$(mktemp -p "${tmp_dir}/sync")
    tmp_b=$(mktemp -p "${tmp_dir}/sync")

    # Write contents to temporary files
    yay -Qqe > "${tmp_a}"
    printf "${packages_to_install[*]}" | tr ' ' '\n' | sort > "${tmp_b}"

    # Install needed packages
    mapfile -t packages_to_add < <(comm -13 "${tmp_a}" "${tmp_b}")
    if [[ -n "${packages_to_add[@]}" ]]; then
        echo "╭──────── Script step ────────╮"
        echo "│ Installing missing packages │"
        echo "╰─────────────────────────────╯"

        yay -Sy
        yay -S "${packages_to_add[@]}"
    fi

    # Remove old packages
    mapfile -t packages_to_remove < <(comm -23 "${tmp_a}" "${tmp_b}")
    if [[ -n "${packages_to_remove[@]}" ]]; then
        echo "╭──────────── Script step ─────────────╮"
        echo "│ Removing packages not needed anymore │"
        echo "╰──────────────────────────────────────╯"

        yay -Rns "${packages_to_remove[@]}"
    fi

    # Remove orphaned packages
    mapfile -t orphaned_packages < <(yay -Qdtq)
    if [[ -n "${orphaned_packages[@]}" ]]; then
        echo "╭─────── Script step ────────╮"
        echo "│ Removing orphaned packages │"
        echo "╰────────────────────────────╯"

        yay -Rns "${orphaned_packages[@]}"
    fi

    ## Clean
    if [[ -n "${orphaned_packages[@]}" ]] || [[ -n "${packages_to_remove[@]}" ]]; then
        echo "╭── Script step ───╮"
        echo "│  Clean packages  │"
        echo "╰──────────────────╯"

        yay -Sc --noconfirm
    fi
}

# Managed packages
ensure_yay_is_installed
sync_packages

# Manual packages
ensure_st_is_installed
